# Generated by Django 5.2.17 on 2026-09-02 08:47

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=255)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tc', models.BooleanField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('teacher', 'Teacher'), ('photographer', 'Photographer'), ('cleaner', 'Cleaner'), ('computer_repair', 'Computer Repair'), ('designer', 'Designer'), ('automobile_engineer', 'Automobile Engineer'), ('barber', 'Barber'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('mason', 'Mason'), ('welder', 'Welder'), ('tile_worker', 'Tile Worker'), ('roofer', 'Roof Repair Specialist'), ('locksmith', 'Locksmith'), ('pest_control', 'Pest Control Specialist'), ('ac_repair', 'AC Repair Technician'), ('refrigerator_repair', 'Refrigerator Repair Technician'), ('washing_machine_repair', 'Washing Machine Repair'), ('water_tank_cleaner', 'Water Tank Cleaner'), ('motorcycle_mechanic', 'Motorcycle Mechanic'), ('car_mechanic', 'Car Mechanic'), ('bike_washer', 'Bike Washing Service'), ('car_washer', 'Car Washing Service'), ('mobile_repair', 'Mobile Repair Technician'), ('laptop_repair', 'Laptop Repair Technician'), ('software_developer', 'Software Developer'), ('web_developer', 'Web Developer'), ('network_technician', 'Network Technician'), ('cctv_technician', 'CCTV Technician'), ('home_tutor', 'Home Tutor'), ('language_tutor', 'Language Tutor'), ('music_teacher', 'Music Teacher'), ('dance_teacher', 'Dance Teacher'), ('beautician', 'Beautician'), ('makeup_artist', 'Makeup Artist'), ('hair_stylist', 'Hair Stylist'), ('massage_therapist', 'Massage Therapist'), ('videographer', 'Videographer'), ('event_planner', 'Event Planner'), ('dj', 'DJ'), ('catering_service', 'Catering Service'), ('cook', 'Cook'), ('accountant', 'Accountant'), ('lawyer', 'Lawyer'), ('translator', 'Translator'), ('real_estate_agent', 'Real Estate Agent'), ('maid', 'Maid/Domestic Helper'), ('nanny', 'Nanny/Babysitter'), ('elderly_care', 'Elderly Care'), ('gardener', 'Gardener'), ('house_mover', 'House Moving Service'), ('florist', 'Florist'), ('tailor', 'Tailor/Dressmaker'), ('cobbler', 'Cobbler/Shoemaker'), ('leather_worker', 'Leather Worker'), ('nurse', 'Nurse/Health Worker'), ('yoga_instructor', 'Yoga Instructor'), ('fitness_trainer', 'Fitness Trainer'), ('physiotherapist', 'Physiotherapist'), ('veterinarian', 'Veterinarian'), ('astrologer', 'Astrologer'), ('geyezer_maintenance', 'Geyezer Maintenance'), ('generator_repair', 'Generator Repair'), ('solar_technician', 'Solar Panel Technician'), ('water_purification', 'Water Purification Technician'), ('blacksmith', 'Blacksmith'), ('woodcarver', 'Woodcarver'), ('metalworker', 'Metalworker'), ('pottery_maker', 'Pottery Maker'), ('courier_service', 'Courier Service'), ('transport_service', 'Transport Service'), ('sports_trainer', 'Sports Trainer'), ('martial_arts_trainer', 'Martial Arts Trainer'), ('swimming_coach', 'Swimming Coach')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('profile', models.ImageField(upload_to='photos/')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.features')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
