# Generated by Django 6.1 on 2026-08-18 07:57

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('teacher', 'Teacher'), ('photographer', 'Photographer'), ('cleaner', 'Cleaner'), ('computer_repair', 'Computer Repair'), ('designer', 'Designer'), ('automobile_engineer', 'Automobile Engineer')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('profile', models.ImageField(upload_to='photos/')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['name'],
            },
        ),
    ]
