# Generated by Django 6.1 on 2026-09-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='category',
            field=models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('teacher', 'Teacher'), ('photographer', 'Photographer'), ('cleaner', 'Cleaner'), ('computer_repair', 'Computer Repair'), ('designer', 'Designer'), ('automobile_engineer', 'Automobile Engineer'), ('barber', 'Barber'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('mason', 'Mason'), ('welder', 'Welder'), ('tile_worker', 'Tile Worker'), ('roofer', 'Roof Repair Specialist'), ('locksmith', 'Locksmith'), ('pest_control', 'Pest Control Specialist'), ('ac_repair', 'AC Repair Technician'), ('refrigerator_repair', 'Refrigerator Repair Technician'), ('washing_machine_repair', 'Washing Machine Repair'), ('water_tank_cleaner', 'Water Tank Cleaner'), ('toilet_tank_cleaner', 'Toilet Tank Cleaner'), ('interior_designer', 'Interior Designer'), ('motorcycle_mechanic', 'Motorcycle Mechanic'), ('car_mechanic', 'Car Mechanic'), ('bike_washer', 'Bike Washing Service'), ('car_washer', 'Car Washing Service'), ('car_rental', 'Car Rental'), ('bike_rental', 'Bike Rental'), ('mobile_repair', 'Mobile Repair Technician'), ('laptop_repair', 'Laptop Repair Technician'), ('software_developer', 'Software Developer'), ('web_developer', 'Web Developer'), ('network_technician', 'Network Technician'), ('cctv_technician', 'CCTV Technician'), ('home_tutor', 'Home Tutor'), ('language_tutor', 'Language Tutor'), ('music_teacher', 'Music Teacher'), ('dance_teacher', 'Dance Teacher'), ('beautician', 'Beautician'), ('makeup_artist', 'Makeup Artist'), ('hair_stylist', 'Hair Stylist'), ('massage_therapist', 'Massage Therapist'), ('videographer', 'Videographer'), ('event_planner', 'Event Planner'), ('dj', 'DJ'), ('catering_service', 'Catering Service'), ('cook', 'Cook'), ('bhajan_toli', 'Bhajan Toli'), ('band_baja', 'Band Baja'), ('panche_baja', 'Panche Baja'), ('flower_decorator', 'Flower Decorator'), ('half_catering', 'Half Catering'), ('accountant', 'Accountant'), ('lawyer', 'Lawyer'), ('translator', 'Translator'), ('real_estate_agent', 'Real Estate Agent'), ('maid', 'Maid/Domestic Helper'), ('nanny', 'Nanny/Babysitter'), ('elderly_care', 'Elderly Care'), ('gardener', 'Gardener'), ('house_mover', 'House Moving Service'), ('florist', 'Florist'), ('tailor', 'Tailor/Dressmaker'), ('cobbler', 'Cobbler/Shoemaker'), ('leather_worker', 'Leather Worker'), ('nurse', 'Nurse/Health Worker'), ('yoga_instructor', 'Yoga Instructor'), ('fitness_trainer', 'Fitness Trainer'), ('physiotherapist', 'Physiotherapist'), ('veterinarian', 'Veterinarian'), ('astrologer', 'Astrologer'), ('geyezer_maintenance', 'Geyezer Maintenance'), ('generator_repair', 'Generator Repair'), ('solar_technician', 'Solar Panel Technician'), ('water_purification', 'Water Purification Technician'), ('blacksmith', 'Blacksmith'), ('woodcarver', 'Woodcarver'), ('metalworker', 'Metalworker'), ('pottery_maker', 'Pottery Maker'), ('courier_service', 'Courier Service'), ('transport_service', 'Transport Service'), ('sports_trainer', 'Sports Trainer'), ('martial_arts_trainer', 'Martial Arts Trainer'), ('swimming_coach', 'Swimming Coach')], max_length=50),
        ),
    ]
